// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AssociateManagerWithOrganizationHandlerFunc turns a function with the right signature into a associate manager with organization handler
type AssociateManagerWithOrganizationHandlerFunc func(AssociateManagerWithOrganizationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AssociateManagerWithOrganizationHandlerFunc) Handle(params AssociateManagerWithOrganizationParams) middleware.Responder {
	return fn(params)
}

// AssociateManagerWithOrganizationHandler interface for that can handle valid associate manager with organization params
type AssociateManagerWithOrganizationHandler interface {
	Handle(AssociateManagerWithOrganizationParams) middleware.Responder
}

// NewAssociateManagerWithOrganization creates a new http.Handler for the associate manager with organization operation
func NewAssociateManagerWithOrganization(ctx *middleware.Context, handler AssociateManagerWithOrganizationHandler) *AssociateManagerWithOrganization {
	return &AssociateManagerWithOrganization{Context: ctx, Handler: handler}
}

/*AssociateManagerWithOrganization swagger:route PUT /organizations/{guid}/managers/{manager_guid} organizations associateManagerWithOrganization

Associate Manager with the Organization

curl --insecure -i %s/v2/organizations/{guid}/managers/{manager_guid} -X PUT -H 'Authorization: %s'

*/
type AssociateManagerWithOrganization struct {
	Context *middleware.Context
	Handler AssociateManagerWithOrganizationHandler
}

func (o *AssociateManagerWithOrganization) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAssociateManagerWithOrganizationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
