// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// GetOrganizationSummaryOKCode is the HTTP code returned for type GetOrganizationSummaryOK
const GetOrganizationSummaryOKCode int = 200

/*GetOrganizationSummaryOK successful response

swagger:response getOrganizationSummaryOK
*/
type GetOrganizationSummaryOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetOrganizationSummaryResponse `json:"body,omitempty"`
}

// NewGetOrganizationSummaryOK creates GetOrganizationSummaryOK with default headers values
func NewGetOrganizationSummaryOK() *GetOrganizationSummaryOK {

	return &GetOrganizationSummaryOK{}
}

// WithPayload adds the payload to the get organization summary o k response
func (o *GetOrganizationSummaryOK) WithPayload(payload *models.GetOrganizationSummaryResponse) *GetOrganizationSummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get organization summary o k response
func (o *GetOrganizationSummaryOK) SetPayload(payload *models.GetOrganizationSummaryResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrganizationSummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
