// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAllSpacesForOrganizationHandlerFunc turns a function with the right signature into a list all spaces for organization handler
type ListAllSpacesForOrganizationHandlerFunc func(ListAllSpacesForOrganizationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllSpacesForOrganizationHandlerFunc) Handle(params ListAllSpacesForOrganizationParams) middleware.Responder {
	return fn(params)
}

// ListAllSpacesForOrganizationHandler interface for that can handle valid list all spaces for organization params
type ListAllSpacesForOrganizationHandler interface {
	Handle(ListAllSpacesForOrganizationParams) middleware.Responder
}

// NewListAllSpacesForOrganization creates a new http.Handler for the list all spaces for organization operation
func NewListAllSpacesForOrganization(ctx *middleware.Context, handler ListAllSpacesForOrganizationHandler) *ListAllSpacesForOrganization {
	return &ListAllSpacesForOrganization{Context: ctx, Handler: handler}
}

/*ListAllSpacesForOrganization swagger:route GET /organizations/{guid}/spaces organizations listAllSpacesForOrganization

List all Spaces for the Organization

curl --insecure -i %s/v2/organizations/{guid}/spaces -X GET -H 'Authorization: %s'

*/
type ListAllSpacesForOrganization struct {
	Context *middleware.Context
	Handler ListAllSpacesForOrganizationHandler
}

func (o *ListAllSpacesForOrganization) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllSpacesForOrganizationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
