// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAllManagersForOrganizationHandlerFunc turns a function with the right signature into a list all managers for organization handler
type ListAllManagersForOrganizationHandlerFunc func(ListAllManagersForOrganizationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllManagersForOrganizationHandlerFunc) Handle(params ListAllManagersForOrganizationParams) middleware.Responder {
	return fn(params)
}

// ListAllManagersForOrganizationHandler interface for that can handle valid list all managers for organization params
type ListAllManagersForOrganizationHandler interface {
	Handle(ListAllManagersForOrganizationParams) middleware.Responder
}

// NewListAllManagersForOrganization creates a new http.Handler for the list all managers for organization operation
func NewListAllManagersForOrganization(ctx *middleware.Context, handler ListAllManagersForOrganizationHandler) *ListAllManagersForOrganization {
	return &ListAllManagersForOrganization{Context: ctx, Handler: handler}
}

/*ListAllManagersForOrganization swagger:route GET /organizations/{guid}/managers organizations listAllManagersForOrganization

List all Managers for the Organization

curl --insecure -i %s/v2/organizations/{guid}/managers -X GET -H 'Authorization: %s'

*/
type ListAllManagersForOrganization struct {
	Context *middleware.Context
	Handler ListAllManagersForOrganizationHandler
}

func (o *ListAllManagersForOrganization) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllManagersForOrganizationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
