// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// ListAllAuditorsForOrganizationOKCode is the HTTP code returned for type ListAllAuditorsForOrganizationOK
const ListAllAuditorsForOrganizationOKCode int = 200

/*ListAllAuditorsForOrganizationOK successful response

swagger:response listAllAuditorsForOrganizationOK
*/
type ListAllAuditorsForOrganizationOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListAllAuditorsForOrganizationResponsePaged `json:"body,omitempty"`
}

// NewListAllAuditorsForOrganizationOK creates ListAllAuditorsForOrganizationOK with default headers values
func NewListAllAuditorsForOrganizationOK() *ListAllAuditorsForOrganizationOK {

	return &ListAllAuditorsForOrganizationOK{}
}

// WithPayload adds the payload to the list all auditors for organization o k response
func (o *ListAllAuditorsForOrganizationOK) WithPayload(payload *models.ListAllAuditorsForOrganizationResponsePaged) *ListAllAuditorsForOrganizationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all auditors for organization o k response
func (o *ListAllAuditorsForOrganizationOK) SetPayload(payload *models.ListAllAuditorsForOrganizationResponsePaged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllAuditorsForOrganizationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
