// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAllBillingManagersForOrganizationHandlerFunc turns a function with the right signature into a list all billing managers for organization handler
type ListAllBillingManagersForOrganizationHandlerFunc func(ListAllBillingManagersForOrganizationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllBillingManagersForOrganizationHandlerFunc) Handle(params ListAllBillingManagersForOrganizationParams) middleware.Responder {
	return fn(params)
}

// ListAllBillingManagersForOrganizationHandler interface for that can handle valid list all billing managers for organization params
type ListAllBillingManagersForOrganizationHandler interface {
	Handle(ListAllBillingManagersForOrganizationParams) middleware.Responder
}

// NewListAllBillingManagersForOrganization creates a new http.Handler for the list all billing managers for organization operation
func NewListAllBillingManagersForOrganization(ctx *middleware.Context, handler ListAllBillingManagersForOrganizationHandler) *ListAllBillingManagersForOrganization {
	return &ListAllBillingManagersForOrganization{Context: ctx, Handler: handler}
}

/*ListAllBillingManagersForOrganization swagger:route GET /organizations/{guid}/billing_managers organizations listAllBillingManagersForOrganization

List all Billing Managers for the Organization

curl --insecure -i %s/v2/organizations/{guid}/billing_managers -X GET -H 'Authorization: %s'

*/
type ListAllBillingManagersForOrganization struct {
	Context *middleware.Context
	Handler ListAllBillingManagersForOrganizationHandler
}

func (o *ListAllBillingManagersForOrganization) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllBillingManagersForOrganizationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
