// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// RemoveUserFromOrganizationCreatedCode is the HTTP code returned for type RemoveUserFromOrganizationCreated
const RemoveUserFromOrganizationCreatedCode int = 201

/*RemoveUserFromOrganizationCreated successful response

swagger:response removeUserFromOrganizationCreated
*/
type RemoveUserFromOrganizationCreated struct {

	/*
	  In: Body
	*/
	Payload *models.RemoveUserFromOrganizationResponse `json:"body,omitempty"`
}

// NewRemoveUserFromOrganizationCreated creates RemoveUserFromOrganizationCreated with default headers values
func NewRemoveUserFromOrganizationCreated() *RemoveUserFromOrganizationCreated {

	return &RemoveUserFromOrganizationCreated{}
}

// WithPayload adds the payload to the remove user from organization created response
func (o *RemoveUserFromOrganizationCreated) WithPayload(payload *models.RemoveUserFromOrganizationResponse) *RemoveUserFromOrganizationCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove user from organization created response
func (o *RemoveUserFromOrganizationCreated) SetPayload(payload *models.RemoveUserFromOrganizationResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveUserFromOrganizationCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
