// Code generated by go-swagger; DO NOT EDIT.

package organization_quota_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListAllOrganizationQuotaDefinitionsParams creates a new ListAllOrganizationQuotaDefinitionsParams object
// no default values defined in spec.
func NewListAllOrganizationQuotaDefinitionsParams() ListAllOrganizationQuotaDefinitionsParams {

	return ListAllOrganizationQuotaDefinitionsParams{}
}

// ListAllOrganizationQuotaDefinitionsParams contains all the bound params for the list all organization quota definitions operation
// typically these are obtained from a http.Request
//
// swagger:parameters listAllOrganizationQuotaDefinitions
type ListAllOrganizationQuotaDefinitionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListAllOrganizationQuotaDefinitionsParams() beforehand.
func (o *ListAllOrganizationQuotaDefinitionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
