// Code generated by go-swagger; DO NOT EDIT.

package organization_quota_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveOrganizationQuotaDefinitionHandlerFunc turns a function with the right signature into a retrieve organization quota definition handler
type RetrieveOrganizationQuotaDefinitionHandlerFunc func(RetrieveOrganizationQuotaDefinitionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveOrganizationQuotaDefinitionHandlerFunc) Handle(params RetrieveOrganizationQuotaDefinitionParams) middleware.Responder {
	return fn(params)
}

// RetrieveOrganizationQuotaDefinitionHandler interface for that can handle valid retrieve organization quota definition params
type RetrieveOrganizationQuotaDefinitionHandler interface {
	Handle(RetrieveOrganizationQuotaDefinitionParams) middleware.Responder
}

// NewRetrieveOrganizationQuotaDefinition creates a new http.Handler for the retrieve organization quota definition operation
func NewRetrieveOrganizationQuotaDefinition(ctx *middleware.Context, handler RetrieveOrganizationQuotaDefinitionHandler) *RetrieveOrganizationQuotaDefinition {
	return &RetrieveOrganizationQuotaDefinition{Context: ctx, Handler: handler}
}

/*RetrieveOrganizationQuotaDefinition swagger:route GET /quota_definitions/{guid} organizationQuotaDefinitions retrieveOrganizationQuotaDefinition

Retrieve a Particular Organization Quota Definition

curl --insecure -i %s/v2/quota_definitions/{guid} -X GET -H 'Authorization: %s'

*/
type RetrieveOrganizationQuotaDefinition struct {
	Context *middleware.Context
	Handler RetrieveOrganizationQuotaDefinitionHandler
}

func (o *RetrieveOrganizationQuotaDefinition) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRetrieveOrganizationQuotaDefinitionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
