categories:
  - title: '🚀 Features'
    labels:
      - 'kind/enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/bug'
  - title: '🧰 Maintenance'
    labels:
      - 'kind/chore'
      - 'kind/dependencies'

exclude-labels:
  - 'area/QA'
  - 'kind/question'
  - 'kind/spike'
  - 'status/apparently external cause'
  - 'status/devops admin'
  - 'status/do not log'
  - 'status/duplicate'
  - 'status/invalid'
  - 'status/later'
  - 'status/overcome by events'
  - 'status/skip-changelog'
  - 'status/wontfix'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
tag-template: 'v$RESOLVED_VERSION'
name-template: 'v$RESOLVED_VERSION'
template: |

  # What's Changed

  $CHANGES

  # Usage

  More info can be found in the [installation instructions](https://docs.epinio.io/installation/install_epinio).

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'kind/enhancement'
      - 'kind/dependencies'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'kind/bug'
      - 'kind/chore'
  default: patch
