// Code generated by go-swagger; DO NOT EDIT.

package space_quota_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// AssociateSpaceWithSpaceQuotaDefinitionCreatedCode is the HTTP code returned for type AssociateSpaceWithSpaceQuotaDefinitionCreated
const AssociateSpaceWithSpaceQuotaDefinitionCreatedCode int = 201

/*AssociateSpaceWithSpaceQuotaDefinitionCreated successful response

swagger:response associateSpaceWithSpaceQuotaDefinitionCreated
*/
type AssociateSpaceWithSpaceQuotaDefinitionCreated struct {

	/*
	  In: Body
	*/
	Payload *models.AssociateSpaceWithSpaceQuotaDefinitionResponse `json:"body,omitempty"`
}

// NewAssociateSpaceWithSpaceQuotaDefinitionCreated creates AssociateSpaceWithSpaceQuotaDefinitionCreated with default headers values
func NewAssociateSpaceWithSpaceQuotaDefinitionCreated() *AssociateSpaceWithSpaceQuotaDefinitionCreated {

	return &AssociateSpaceWithSpaceQuotaDefinitionCreated{}
}

// WithPayload adds the payload to the associate space with space quota definition created response
func (o *AssociateSpaceWithSpaceQuotaDefinitionCreated) WithPayload(payload *models.AssociateSpaceWithSpaceQuotaDefinitionResponse) *AssociateSpaceWithSpaceQuotaDefinitionCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the associate space with space quota definition created response
func (o *AssociateSpaceWithSpaceQuotaDefinitionCreated) SetPayload(payload *models.AssociateSpaceWithSpaceQuotaDefinitionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AssociateSpaceWithSpaceQuotaDefinitionCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
