// Code generated by go-swagger; DO NOT EDIT.

package space_quota_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// ListAllSpaceQuotaDefinitionsOKCode is the HTTP code returned for type ListAllSpaceQuotaDefinitionsOK
const ListAllSpaceQuotaDefinitionsOKCode int = 200

/*ListAllSpaceQuotaDefinitionsOK successful response

swagger:response listAllSpaceQuotaDefinitionsOK
*/
type ListAllSpaceQuotaDefinitionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListAllSpaceQuotaDefinitionsResponsePaged `json:"body,omitempty"`
}

// NewListAllSpaceQuotaDefinitionsOK creates ListAllSpaceQuotaDefinitionsOK with default headers values
func NewListAllSpaceQuotaDefinitionsOK() *ListAllSpaceQuotaDefinitionsOK {

	return &ListAllSpaceQuotaDefinitionsOK{}
}

// WithPayload adds the payload to the list all space quota definitions o k response
func (o *ListAllSpaceQuotaDefinitionsOK) WithPayload(payload *models.ListAllSpaceQuotaDefinitionsResponsePaged) *ListAllSpaceQuotaDefinitionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all space quota definitions o k response
func (o *ListAllSpaceQuotaDefinitionsOK) SetPayload(payload *models.ListAllSpaceQuotaDefinitionsResponsePaged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllSpaceQuotaDefinitionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
