run:
  go: "1.18"
  deadline: 20s

  # don't report issues from these dirs
  skip-dirs:
    - vendor
    - assets

  # skip generated files
  skip-files:
  - ".*_fake.go$"
  - "fake_.*.go$"

linters-settings:
  revive:
    rules:
    - name: blank-imports
      severity: warning
  funlen:
    # Checks the number of lines in a function. Default: 60
    lines: 270
    # Checks the number of statements in a function. Default: 40
    statements: 110

issues:
  exclude-rules:
  - linters:
    - gocyclo
    - dupl
    - errcheck
    - gosec
    path: _test\.go

linters:
  disable-all: true
  enable:
  # default linters
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
  
  # extra
  - dupl
  - funlen
  - gocyclo
  - goimports
  - gosec
  - misspell
  - nakedret
  - revive
  - unparam
