#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Retries a command on failure.
# $1 - the max number of attempts
# $2... - the command to run
retry() {
    local -r -i max_attempts="$1"; shift
    local -r cmd="$@"
    local -i attempt_num=1

    until bash -c "$cmd"
    do
        if (( attempt_num == max_attempts ))
        then
            echo -n "Attempt $attempt_num failed and there are no more attempts left!"
            return 1
        else
            echo -n "."
            attempt_num=$(( attempt_num+1 ))
            sleep 1
        fi
    done
    echo
}

export -f retry

cmd=$(basename "${0}")
if [ "${cmd}" = "carrier" ]; then
  command="$1"
  shift

echo "$@"

  case "${command}" in
    push)       "$dir/push" "$@" ;;
    delete)     "$dir/delete" "$@" ;;
    install)    "$dir/install" "$@" ;;
    uninstall)  "$dir/uninstall" "$@" ;;
    apps)       "$dir/apps" "$@" ;;
    *)
      echo "Usage: carrier <command> [flags]"
      echo "push            - Push an app"
      echo "delete          - Delete an app"
      echo "install         - Installs carrier on a Kubernetes cluster"
      echo "uninstall       - Uninstalls carrier"
      echo "apps            - Lists apps"
    ;;
  esac
fi
