#!/bin/bash

# install traefik
./traefik/install
./traefik/wait

# get a public IP
external_ip=$(kubectl get svc -A --field-selector='metadata.name=traefik' -o json | jq -r .items[0].status.loadBalancer.ingress[0].ip)
echo "Will use public IP address ${external_ip}"

cmd=$(basename "${0}")
if [ "${cmd}" = "install" ]; then
  command="$1"
  shift

  if [ -z "${command}" ]; then
    # install quarks
    ./quarks/install

    # install gitea
    ./gitea/install "$external_ip"

    # install eirini
    ./eirini/install "${external_ip}"

    # install registry
    ./container-registry/install

    # install tekton
    ./tekton/install "$external_ip"
  else
    ./$command/install "$external_ip"
  fi
fi
