#!/bin/bash

echo -n Docker Registry Username: 
read registry_username
echo
echo -n Docker Registry Password: 
read -s registry_password
echo

# install nginx
./ingress/install
./ingress/wait

# get a public IP
external_ip=$(kubectl get svc -n ingress-nginx  ingress-nginx-controller -o json | jq -r .status.loadBalancer.ingress[0].ip)
echo "Will use public IP address ${external_ip}"

# install quarks
./quarks/install

# install gitea
./gitea/install "$external_ip"

# install kpack
./kpack/install "$registry_username" "$registry_password"

# install drone
./drone/install "$external_ip"

# install eirini
./eirini/install

# configure drone
./drone-gitea/install "$external_ip"

# wait
