#!/bin/bash

# uninstall traefik
./traefik/uninstall &

# uninstall quarks
./quarks/uninstall &

# uninstall gitea
./gitea/uninstall &

# uninstall kpack
./kpack/uninstall &

# uninstall drone
./drone/uninstall &

# uninstall eirini
./eirini/uninstall &

wait
