---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksJob
metadata:
  name: gitea-app
  namespace: staging
spec:
  template:
    backoffLimit: 6
    spec:
      template:
        spec:
          containers:
            - name: create-app
              image: curlimages/curl:7.73.0
              command: ["/bin/sh"]
              args:
              - "-c"
              - |
                curl -sb -X POST "http://dev:changeme@gitea.34.68.88.15.nip.io/api/v1/user/applications/oauth2" \
                -H "accept: application/json" \
                -H "Content-Type: application/json" \
                -d "{  \"name\": \"drone\",  \"redirect_uris\": [\"http://gitea.34.68.88.15.nip.io/login\" ]}"
          restartPolicy: Never
          terminationGracePeriodSeconds: 1
  trigger:
    strategy: once
  output:
    outputMap:
      jsonout:
        app-secret.json:
          name: drone-app-secret
          versioned: false
    secretLabels:
      app: carrier
