#!/bin/bash

function log() {
  echo -e "\e[35mdrone> \e[32m$1\e[39m"
}

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Removing drone."
helm delete drone --namespace drone >> "$HOME/.carrier.log" 2>&1

log "Removing ingress for drone."
kubectl delete -f "$dir/ingress.yaml" >> "$HOME/.carrier.log" 2>&1

log "Removing drone namespace."
kubectl delete ns drone >> "$HOME/.carrier.log" 2>&1

log "Removing drone runner."
helm remove drone-runner-kube --namespace drone >> "$HOME/.carrier.log" 2>&1

log "Removing drone runner namespace."
kubectl delete ns drone >> "$HOME/.carrier.log" 2>&1

log "Removing drone runner service account."
kubectl delete -f "$dir/drone-runner-service-account.yaml" >> "$HOME/.carrier.log" 2>&1

log "Removing drone runner namespace."
kubectl delete ns drone-runner-kube >> "$HOME/.carrier.log" 2>&1
