// Code generated by go-swagger; DO NOT EDIT.

package user_provided_service_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// CreateUserProvidedServiceInstanceCreatedCode is the HTTP code returned for type CreateUserProvidedServiceInstanceCreated
const CreateUserProvidedServiceInstanceCreatedCode int = 201

/*CreateUserProvidedServiceInstanceCreated successful response

swagger:response createUserProvidedServiceInstanceCreated
*/
type CreateUserProvidedServiceInstanceCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CreateUserProvidedServiceInstanceResponse `json:"body,omitempty"`
}

// NewCreateUserProvidedServiceInstanceCreated creates CreateUserProvidedServiceInstanceCreated with default headers values
func NewCreateUserProvidedServiceInstanceCreated() *CreateUserProvidedServiceInstanceCreated {

	return &CreateUserProvidedServiceInstanceCreated{}
}

// WithPayload adds the payload to the create user provided service instance created response
func (o *CreateUserProvidedServiceInstanceCreated) WithPayload(payload *models.CreateUserProvidedServiceInstanceResponse) *CreateUserProvidedServiceInstanceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create user provided service instance created response
func (o *CreateUserProvidedServiceInstanceCreated) SetPayload(payload *models.CreateUserProvidedServiceInstanceResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateUserProvidedServiceInstanceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
