// Code generated by go-swagger; DO NOT EDIT.

package user_provided_service_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteUserProvidedServiceInstanceHandlerFunc turns a function with the right signature into a delete user provided service instance handler
type DeleteUserProvidedServiceInstanceHandlerFunc func(DeleteUserProvidedServiceInstanceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserProvidedServiceInstanceHandlerFunc) Handle(params DeleteUserProvidedServiceInstanceParams) middleware.Responder {
	return fn(params)
}

// DeleteUserProvidedServiceInstanceHandler interface for that can handle valid delete user provided service instance params
type DeleteUserProvidedServiceInstanceHandler interface {
	Handle(DeleteUserProvidedServiceInstanceParams) middleware.Responder
}

// NewDeleteUserProvidedServiceInstance creates a new http.Handler for the delete user provided service instance operation
func NewDeleteUserProvidedServiceInstance(ctx *middleware.Context, handler DeleteUserProvidedServiceInstanceHandler) *DeleteUserProvidedServiceInstance {
	return &DeleteUserProvidedServiceInstance{Context: ctx, Handler: handler}
}

/*DeleteUserProvidedServiceInstance swagger:route DELETE /user_provided_service_instances/{guid} userProvidedServiceInstances deleteUserProvidedServiceInstance

Delete a Particular User Provided Service Instance

curl --insecure -i %s/v2/user_provided_service_instances/{guid} -X DELETE -H 'Authorization: %s'

*/
type DeleteUserProvidedServiceInstance struct {
	Context *middleware.Context
	Handler DeleteUserProvidedServiceInstanceHandler
}

func (o *DeleteUserProvidedServiceInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteUserProvidedServiceInstanceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
