// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteRouteNoContentCode is the HTTP code returned for type DeleteRouteNoContent
const DeleteRouteNoContentCode int = 204

/*DeleteRouteNoContent successful response

swagger:response deleteRouteNoContent
*/
type DeleteRouteNoContent struct {
}

// NewDeleteRouteNoContent creates DeleteRouteNoContent with default headers values
func NewDeleteRouteNoContent() *DeleteRouteNoContent {

	return &DeleteRouteNoContent{}
}

// WriteResponse to the client
func (o *DeleteRouteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
