// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// ListAllRoutesOKCode is the HTTP code returned for type ListAllRoutesOK
const ListAllRoutesOKCode int = 200

/*ListAllRoutesOK successful response

swagger:response listAllRoutesOK
*/
type ListAllRoutesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListAllRoutesResponsePaged `json:"body,omitempty"`
}

// NewListAllRoutesOK creates ListAllRoutesOK with default headers values
func NewListAllRoutesOK() *ListAllRoutesOK {

	return &ListAllRoutesOK{}
}

// WithPayload adds the payload to the list all routes o k response
func (o *ListAllRoutesOK) WithPayload(payload *models.ListAllRoutesResponsePaged) *ListAllRoutesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all routes o k response
func (o *ListAllRoutesOK) SetPayload(payload *models.ListAllRoutesResponsePaged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllRoutesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
