#!/bin/bash

function log() {
  echo -e "\e[35meirini> \e[32m$1\e[39m"
}

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Removing eirini."

cd "$dir/eirini-release"
./deploy/scripts/cleanup.sh >> "$HOME/.carrier.log" 2>&1

log "Cleaning up app namespace."
kubectl delete -f "$dir/app-namespace.yaml" >> "$HOME/.carrier.log" 2>&1
