// Code generated by go-swagger; DO NOT EDIT.

package service_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveServiceInstanceHandlerFunc turns a function with the right signature into a retrieve service instance handler
type RetrieveServiceInstanceHandlerFunc func(RetrieveServiceInstanceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveServiceInstanceHandlerFunc) Handle(params RetrieveServiceInstanceParams) middleware.Responder {
	return fn(params)
}

// RetrieveServiceInstanceHandler interface for that can handle valid retrieve service instance params
type RetrieveServiceInstanceHandler interface {
	Handle(RetrieveServiceInstanceParams) middleware.Responder
}

// NewRetrieveServiceInstance creates a new http.Handler for the retrieve service instance operation
func NewRetrieveServiceInstance(ctx *middleware.Context, handler RetrieveServiceInstanceHandler) *RetrieveServiceInstance {
	return &RetrieveServiceInstance{Context: ctx, Handler: handler}
}

/*RetrieveServiceInstance swagger:route GET /service_instances/{guid} serviceInstances retrieveServiceInstance

Retrieve a Particular Service Instance

curl --insecure -i %s/v2/service_instances/{guid} -X GET -H 'Authorization: %s'

*/
type RetrieveServiceInstance struct {
	Context *middleware.Context
	Handler RetrieveServiceInstanceHandler
}

func (o *RetrieveServiceInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRetrieveServiceInstanceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
