// Code generated by go-swagger; DO NOT EDIT.

package security_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// ListAllSecurityGroupsOKCode is the HTTP code returned for type ListAllSecurityGroupsOK
const ListAllSecurityGroupsOKCode int = 200

/*ListAllSecurityGroupsOK successful response

swagger:response listAllSecurityGroupsOK
*/
type ListAllSecurityGroupsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListAllSecurityGroupsResponsePaged `json:"body,omitempty"`
}

// NewListAllSecurityGroupsOK creates ListAllSecurityGroupsOK with default headers values
func NewListAllSecurityGroupsOK() *ListAllSecurityGroupsOK {

	return &ListAllSecurityGroupsOK{}
}

// WithPayload adds the payload to the list all security groups o k response
func (o *ListAllSecurityGroupsOK) WithPayload(payload *models.ListAllSecurityGroupsResponsePaged) *ListAllSecurityGroupsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all security groups o k response
func (o *ListAllSecurityGroupsOK) SetPayload(payload *models.ListAllSecurityGroupsResponsePaged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllSecurityGroupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
