// Code generated by go-swagger; DO NOT EDIT.

package security_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAllSpacesForSecurityGroupHandlerFunc turns a function with the right signature into a list all spaces for security group handler
type ListAllSpacesForSecurityGroupHandlerFunc func(ListAllSpacesForSecurityGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllSpacesForSecurityGroupHandlerFunc) Handle(params ListAllSpacesForSecurityGroupParams) middleware.Responder {
	return fn(params)
}

// ListAllSpacesForSecurityGroupHandler interface for that can handle valid list all spaces for security group params
type ListAllSpacesForSecurityGroupHandler interface {
	Handle(ListAllSpacesForSecurityGroupParams) middleware.Responder
}

// NewListAllSpacesForSecurityGroup creates a new http.Handler for the list all spaces for security group operation
func NewListAllSpacesForSecurityGroup(ctx *middleware.Context, handler ListAllSpacesForSecurityGroupHandler) *ListAllSpacesForSecurityGroup {
	return &ListAllSpacesForSecurityGroup{Context: ctx, Handler: handler}
}

/*ListAllSpacesForSecurityGroup swagger:route GET /security_groups/{guid}/spaces securityGroups listAllSpacesForSecurityGroup

List all Spaces for the Security Group

curl --insecure -i %s/v2/security_groups/{guid}/spaces -X GET -H 'Authorization: %s'

*/
type ListAllSpacesForSecurityGroup struct {
	Context *middleware.Context
	Handler ListAllSpacesForSecurityGroupHandler
}

func (o *ListAllSpacesForSecurityGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllSpacesForSecurityGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
