// Code generated by go-swagger; DO NOT EDIT.

package security_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveSecurityGroupHandlerFunc turns a function with the right signature into a retrieve security group handler
type RetrieveSecurityGroupHandlerFunc func(RetrieveSecurityGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveSecurityGroupHandlerFunc) Handle(params RetrieveSecurityGroupParams) middleware.Responder {
	return fn(params)
}

// RetrieveSecurityGroupHandler interface for that can handle valid retrieve security group params
type RetrieveSecurityGroupHandler interface {
	Handle(RetrieveSecurityGroupParams) middleware.Responder
}

// NewRetrieveSecurityGroup creates a new http.Handler for the retrieve security group operation
func NewRetrieveSecurityGroup(ctx *middleware.Context, handler RetrieveSecurityGroupHandler) *RetrieveSecurityGroup {
	return &RetrieveSecurityGroup{Context: ctx, Handler: handler}
}

/*RetrieveSecurityGroup swagger:route GET /security_groups/{guid} securityGroups retrieveSecurityGroup

Retrieve a Particular Security Group

curl --insecure -i %s/v2/security_groups/{guid} -X GET -H 'Authorization: %s'

*/
type RetrieveSecurityGroup struct {
	Context *middleware.Context
	Handler RetrieveSecurityGroupHandler
}

func (o *RetrieveSecurityGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRetrieveSecurityGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
