// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// GetServiceInstanceCreationFeatureFlagOKCode is the HTTP code returned for type GetServiceInstanceCreationFeatureFlagOK
const GetServiceInstanceCreationFeatureFlagOKCode int = 200

/*GetServiceInstanceCreationFeatureFlagOK successful response

swagger:response getServiceInstanceCreationFeatureFlagOK
*/
type GetServiceInstanceCreationFeatureFlagOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetServiceInstanceCreationFeatureFlagResponseResource `json:"body,omitempty"`
}

// NewGetServiceInstanceCreationFeatureFlagOK creates GetServiceInstanceCreationFeatureFlagOK with default headers values
func NewGetServiceInstanceCreationFeatureFlagOK() *GetServiceInstanceCreationFeatureFlagOK {

	return &GetServiceInstanceCreationFeatureFlagOK{}
}

// WithPayload adds the payload to the get service instance creation feature flag o k response
func (o *GetServiceInstanceCreationFeatureFlagOK) WithPayload(payload *models.GetServiceInstanceCreationFeatureFlagResponseResource) *GetServiceInstanceCreationFeatureFlagOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service instance creation feature flag o k response
func (o *GetServiceInstanceCreationFeatureFlagOK) SetPayload(payload *models.GetServiceInstanceCreationFeatureFlagResponseResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceInstanceCreationFeatureFlagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
