// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// GetRouteCreationFeatureFlagOKCode is the HTTP code returned for type GetRouteCreationFeatureFlagOK
const GetRouteCreationFeatureFlagOKCode int = 200

/*GetRouteCreationFeatureFlagOK successful response

swagger:response getRouteCreationFeatureFlagOK
*/
type GetRouteCreationFeatureFlagOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetRouteCreationFeatureFlagResponse `json:"body,omitempty"`
}

// NewGetRouteCreationFeatureFlagOK creates GetRouteCreationFeatureFlagOK with default headers values
func NewGetRouteCreationFeatureFlagOK() *GetRouteCreationFeatureFlagOK {

	return &GetRouteCreationFeatureFlagOK{}
}

// WithPayload adds the payload to the get route creation feature flag o k response
func (o *GetRouteCreationFeatureFlagOK) WithPayload(payload *models.GetRouteCreationFeatureFlagResponse) *GetRouteCreationFeatureFlagOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get route creation feature flag o k response
func (o *GetRouteCreationFeatureFlagOK) SetPayload(payload *models.GetRouteCreationFeatureFlagResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRouteCreationFeatureFlagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
