// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAppBitsUploadFeatureFlagHandlerFunc turns a function with the right signature into a get app bits upload feature flag handler
type GetAppBitsUploadFeatureFlagHandlerFunc func(GetAppBitsUploadFeatureFlagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppBitsUploadFeatureFlagHandlerFunc) Handle(params GetAppBitsUploadFeatureFlagParams) middleware.Responder {
	return fn(params)
}

// GetAppBitsUploadFeatureFlagHandler interface for that can handle valid get app bits upload feature flag params
type GetAppBitsUploadFeatureFlagHandler interface {
	Handle(GetAppBitsUploadFeatureFlagParams) middleware.Responder
}

// NewGetAppBitsUploadFeatureFlag creates a new http.Handler for the get app bits upload feature flag operation
func NewGetAppBitsUploadFeatureFlag(ctx *middleware.Context, handler GetAppBitsUploadFeatureFlagHandler) *GetAppBitsUploadFeatureFlag {
	return &GetAppBitsUploadFeatureFlag{Context: ctx, Handler: handler}
}

/*GetAppBitsUploadFeatureFlag swagger:route GET /config/feature_flags/app_bits_upload featureFlags getAppBitsUploadFeatureFlag

Get the App Bits Upload feature flag

curl --insecure -i %s/v2/config/feature_flags/app_bits_upload -X GET -H 'Authorization: %s'

*/
type GetAppBitsUploadFeatureFlag struct {
	Context *middleware.Context
	Handler GetAppBitsUploadFeatureFlagHandler
}

func (o *GetAppBitsUploadFeatureFlag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAppBitsUploadFeatureFlagParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
