// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// GetUserOrgCreationFeatureFlagOKCode is the HTTP code returned for type GetUserOrgCreationFeatureFlagOK
const GetUserOrgCreationFeatureFlagOKCode int = 200

/*GetUserOrgCreationFeatureFlagOK successful response

swagger:response getUserOrgCreationFeatureFlagOK
*/
type GetUserOrgCreationFeatureFlagOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetUserOrgCreationFeatureFlagResponseResource `json:"body,omitempty"`
}

// NewGetUserOrgCreationFeatureFlagOK creates GetUserOrgCreationFeatureFlagOK with default headers values
func NewGetUserOrgCreationFeatureFlagOK() *GetUserOrgCreationFeatureFlagOK {

	return &GetUserOrgCreationFeatureFlagOK{}
}

// WithPayload adds the payload to the get user org creation feature flag o k response
func (o *GetUserOrgCreationFeatureFlagOK) WithPayload(payload *models.GetUserOrgCreationFeatureFlagResponseResource) *GetUserOrgCreationFeatureFlagOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user org creation feature flag o k response
func (o *GetUserOrgCreationFeatureFlagOK) SetPayload(payload *models.GetUserOrgCreationFeatureFlagResponseResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserOrgCreationFeatureFlagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
