// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// AssociateRouteWithAppCreatedCode is the HTTP code returned for type AssociateRouteWithAppCreated
const AssociateRouteWithAppCreatedCode int = 201

/*AssociateRouteWithAppCreated successful response

swagger:response associateRouteWithAppCreated
*/
type AssociateRouteWithAppCreated struct {

	/*
	  In: Body
	*/
	Payload *models.AssociateRouteWithAppResponseResource `json:"body,omitempty"`
}

// NewAssociateRouteWithAppCreated creates AssociateRouteWithAppCreated with default headers values
func NewAssociateRouteWithAppCreated() *AssociateRouteWithAppCreated {

	return &AssociateRouteWithAppCreated{}
}

// WithPayload adds the payload to the associate route with app created response
func (o *AssociateRouteWithAppCreated) WithPayload(payload *models.AssociateRouteWithAppResponseResource) *AssociateRouteWithAppCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the associate route with app created response
func (o *AssociateRouteWithAppCreated) SetPayload(payload *models.AssociateRouteWithAppResponseResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AssociateRouteWithAppCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
