// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// CreateAppCreatedCode is the HTTP code returned for type CreateAppCreated
const CreateAppCreatedCode int = 201

/*CreateAppCreated successful response

swagger:response createAppCreated
*/
type CreateAppCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CreateAppResponseResource `json:"body,omitempty"`
}

// NewCreateAppCreated creates CreateAppCreated with default headers values
func NewCreateAppCreated() *CreateAppCreated {

	return &CreateAppCreated{}
}

// WithPayload adds the payload to the create app created response
func (o *CreateAppCreated) WithPayload(payload *models.CreateAppResponseResource) *CreateAppCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create app created response
func (o *CreateAppCreated) SetPayload(payload *models.CreateAppResponseResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAppCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
