// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DownloadsBitsForAppHandlerFunc turns a function with the right signature into a downloads bits for app handler
type DownloadsBitsForAppHandlerFunc func(DownloadsBitsForAppParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DownloadsBitsForAppHandlerFunc) Handle(params DownloadsBitsForAppParams) middleware.Responder {
	return fn(params)
}

// DownloadsBitsForAppHandler interface for that can handle valid downloads bits for app params
type DownloadsBitsForAppHandler interface {
	Handle(DownloadsBitsForAppParams) middleware.Responder
}

// NewDownloadsBitsForApp creates a new http.Handler for the downloads bits for app operation
func NewDownloadsBitsForApp(ctx *middleware.Context, handler DownloadsBitsForAppHandler) *DownloadsBitsForApp {
	return &DownloadsBitsForApp{Context: ctx, Handler: handler}
}

/*DownloadsBitsForApp swagger:route GET /apps/{guid}/download apps downloadsBitsForApp

Downloads the bits for an App

curl --insecure -i %s/v2/apps/{guid}/download -X GET -H 'Authorization: %s'

*/
type DownloadsBitsForApp struct {
	Context *middleware.Context
	Handler DownloadsBitsForAppHandler
}

func (o *DownloadsBitsForApp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDownloadsBitsForAppParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
