// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownloadsBitsForAppFoundCode is the HTTP code returned for type DownloadsBitsForAppFound
const DownloadsBitsForAppFoundCode int = 302

/*DownloadsBitsForAppFound successful response

swagger:response downloadsBitsForAppFound
*/
type DownloadsBitsForAppFound struct {
}

// NewDownloadsBitsForAppFound creates DownloadsBitsForAppFound with default headers values
func NewDownloadsBitsForAppFound() *DownloadsBitsForAppFound {

	return &DownloadsBitsForAppFound{}
}

// WriteResponse to the client
func (o *DownloadsBitsForAppFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}
