// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDetailedStatsForStartedAppHandlerFunc turns a function with the right signature into a get detailed stats for started app handler
type GetDetailedStatsForStartedAppHandlerFunc func(GetDetailedStatsForStartedAppParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDetailedStatsForStartedAppHandlerFunc) Handle(params GetDetailedStatsForStartedAppParams) middleware.Responder {
	return fn(params)
}

// GetDetailedStatsForStartedAppHandler interface for that can handle valid get detailed stats for started app params
type GetDetailedStatsForStartedAppHandler interface {
	Handle(GetDetailedStatsForStartedAppParams) middleware.Responder
}

// NewGetDetailedStatsForStartedApp creates a new http.Handler for the get detailed stats for started app operation
func NewGetDetailedStatsForStartedApp(ctx *middleware.Context, handler GetDetailedStatsForStartedAppHandler) *GetDetailedStatsForStartedApp {
	return &GetDetailedStatsForStartedApp{Context: ctx, Handler: handler}
}

/*GetDetailedStatsForStartedApp swagger:route GET /apps/{guid}/stats apps getDetailedStatsForStartedApp

Get detailed stats for a STARTED App

curl --insecure -i %s/v2/apps/{guid}/stats -X GET -H 'Authorization: %s'

*/
type GetDetailedStatsForStartedApp struct {
	Context *middleware.Context
	Handler GetDetailedStatsForStartedAppHandler
}

func (o *GetDetailedStatsForStartedApp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDetailedStatsForStartedAppParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
