// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// ListAllAppsOKCode is the HTTP code returned for type ListAllAppsOK
const ListAllAppsOKCode int = 200

/*ListAllAppsOK successful response

swagger:response listAllAppsOK
*/
type ListAllAppsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListAllAppsResponsePaged `json:"body,omitempty"`
}

// NewListAllAppsOK creates ListAllAppsOK with default headers values
func NewListAllAppsOK() *ListAllAppsOK {

	return &ListAllAppsOK{}
}

// WithPayload adds the payload to the list all apps o k response
func (o *ListAllAppsOK) WithPayload(payload *models.ListAllAppsResponsePaged) *ListAllAppsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all apps o k response
func (o *ListAllAppsOK) SetPayload(payload *models.ListAllAppsResponsePaged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllAppsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
