// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// ListAllServiceBindingsForAppOKCode is the HTTP code returned for type ListAllServiceBindingsForAppOK
const ListAllServiceBindingsForAppOKCode int = 200

/*ListAllServiceBindingsForAppOK successful response

swagger:response listAllServiceBindingsForAppOK
*/
type ListAllServiceBindingsForAppOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListAllServiceBindingsForAppResponsePaged `json:"body,omitempty"`
}

// NewListAllServiceBindingsForAppOK creates ListAllServiceBindingsForAppOK with default headers values
func NewListAllServiceBindingsForAppOK() *ListAllServiceBindingsForAppOK {

	return &ListAllServiceBindingsForAppOK{}
}

// WithPayload adds the payload to the list all service bindings for app o k response
func (o *ListAllServiceBindingsForAppOK) WithPayload(payload *models.ListAllServiceBindingsForAppResponsePaged) *ListAllServiceBindingsForAppOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all service bindings for app o k response
func (o *ListAllServiceBindingsForAppOK) SetPayload(payload *models.ListAllServiceBindingsForAppResponsePaged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllServiceBindingsForAppOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
