// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListAllAppsParams creates a new ListAllAppsParams object
// no default values defined in spec.
func NewListAllAppsParams() ListAllAppsParams {

	return ListAllAppsParams{}
}

// ListAllAppsParams contains all the bound params for the list all apps operation
// typically these are obtained from a http.Request
//
// swagger:parameters listAllApps
type ListAllAppsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListAllAppsParams() beforehand.
func (o *ListAllAppsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
