// Code generated by go-swagger; DO NOT EDIT.

package environment_variable_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GettingContentsOfStagingEnvironmentVariableGroupHandlerFunc turns a function with the right signature into a getting contents of staging environment variable group handler
type GettingContentsOfStagingEnvironmentVariableGroupHandlerFunc func(GettingContentsOfStagingEnvironmentVariableGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GettingContentsOfStagingEnvironmentVariableGroupHandlerFunc) Handle(params GettingContentsOfStagingEnvironmentVariableGroupParams) middleware.Responder {
	return fn(params)
}

// GettingContentsOfStagingEnvironmentVariableGroupHandler interface for that can handle valid getting contents of staging environment variable group params
type GettingContentsOfStagingEnvironmentVariableGroupHandler interface {
	Handle(GettingContentsOfStagingEnvironmentVariableGroupParams) middleware.Responder
}

// NewGettingContentsOfStagingEnvironmentVariableGroup creates a new http.Handler for the getting contents of staging environment variable group operation
func NewGettingContentsOfStagingEnvironmentVariableGroup(ctx *middleware.Context, handler GettingContentsOfStagingEnvironmentVariableGroupHandler) *GettingContentsOfStagingEnvironmentVariableGroup {
	return &GettingContentsOfStagingEnvironmentVariableGroup{Context: ctx, Handler: handler}
}

/*GettingContentsOfStagingEnvironmentVariableGroup swagger:route GET /config/environment_variable_groups/staging environmentVariableGroups gettingContentsOfStagingEnvironmentVariableGroup

Getting the contents of the staging environment variable group

curl --insecure -i %s/v2/config/environment_variable_groups/staging -X GET -H 'Authorization: %s'

*/
type GettingContentsOfStagingEnvironmentVariableGroup struct {
	Context *middleware.Context
	Handler GettingContentsOfStagingEnvironmentVariableGroupHandler
}

func (o *GettingContentsOfStagingEnvironmentVariableGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGettingContentsOfStagingEnvironmentVariableGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
