// Code generated by go-swagger; DO NOT EDIT.

package environment_variable_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateContentsOfStagingEnvironmentVariableGroupHandlerFunc turns a function with the right signature into a update contents of staging environment variable group handler
type UpdateContentsOfStagingEnvironmentVariableGroupHandlerFunc func(UpdateContentsOfStagingEnvironmentVariableGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateContentsOfStagingEnvironmentVariableGroupHandlerFunc) Handle(params UpdateContentsOfStagingEnvironmentVariableGroupParams) middleware.Responder {
	return fn(params)
}

// UpdateContentsOfStagingEnvironmentVariableGroupHandler interface for that can handle valid update contents of staging environment variable group params
type UpdateContentsOfStagingEnvironmentVariableGroupHandler interface {
	Handle(UpdateContentsOfStagingEnvironmentVariableGroupParams) middleware.Responder
}

// NewUpdateContentsOfStagingEnvironmentVariableGroup creates a new http.Handler for the update contents of staging environment variable group operation
func NewUpdateContentsOfStagingEnvironmentVariableGroup(ctx *middleware.Context, handler UpdateContentsOfStagingEnvironmentVariableGroupHandler) *UpdateContentsOfStagingEnvironmentVariableGroup {
	return &UpdateContentsOfStagingEnvironmentVariableGroup{Context: ctx, Handler: handler}
}

/*UpdateContentsOfStagingEnvironmentVariableGroup swagger:route PUT /config/environment_variable_groups/staging environmentVariableGroups updateContentsOfStagingEnvironmentVariableGroup

Updating the contents of the staging environment variable group

curl --insecure -i %s/v2/config/environment_variable_groups/staging -X PUT -H 'Authorization: %s' -d '%s'

*/
type UpdateContentsOfStagingEnvironmentVariableGroup struct {
	Context *middleware.Context
	Handler UpdateContentsOfStagingEnvironmentVariableGroupHandler
}

func (o *UpdateContentsOfStagingEnvironmentVariableGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateContentsOfStagingEnvironmentVariableGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
