---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: epinio-server
  namespace: epinio

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: epinio-server
rules:
- apiGroups:
  - "tekton.dev"
  resources:
  - pipelineruns
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - create
  - delete
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - update
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - servicebindings
  verbs:
  - create
  - get
  - delete
  - list
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - serviceinstances
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
- apiGroups:
  - "cert-manager.io"
  resources:
  - certificates
  verbs:
  - create
- apiGroups:
  - application.epinio.io
  resources:
  - apps
  verbs:
  - get
  - list
  - create
  - delete
  - patch
- apiGroups:
  - "metrics.k8s.io"
  resources:
  - pods
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: epinio-server-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: epinio-server
subjects:
- kind: ServiceAccount
  name: epinio-server
  namespace: epinio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: epinio
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: epinio-server
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: ##current_epinio_version##
  name: epinio-server
  namespace: epinio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: epinio-server
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: epinio-server
      app.kubernetes.io/part-of: epinio
  template:
    metadata:
      labels:
        app.kubernetes.io/component: epinio-server
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: epinio-server
        app.kubernetes.io/part-of: epinio
        app.kubernetes.io/version: ##current_epinio_version##
      name: epinio-server
    spec:
      serviceAccountName: epinio-server
      containers:
        - command: ["/epinio", "server"]
          args: ["--port", "80"]
          env:
            - name: ACCESS_CONTROL_ALLOW_ORIGIN
              value: "##access_control_allow_origin##"
            - name: EPINIO_TIMEOUT_MULTIPLIER
              value: "##epinio_timeout_multiplier##"
            - name: SESSION_KEY
              value: "##epinio_session_key##"
            - name: TLS_ISSUER
              value: ##tls_issuer##
            - name: TRACE_LEVEL
              value: "##trace_level##"
            - name: FORCE_KUBE_INTERNAL_REGISTRY_TLS
              value: "##force_kube_internal_registry_tls##"
          image: splatform/epinio-server:##current_epinio_version##
          livenessProbe:
            httpGet:
              path: /ready
              port: 80
          name: epinio-server
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 65532

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: epinio
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: epinio-server
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: ##current_epinio_version##
  name: epinio-server
  namespace: epinio
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: epinio-server
