// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// ListAllServicePlansForServiceOKCode is the HTTP code returned for type ListAllServicePlansForServiceOK
const ListAllServicePlansForServiceOKCode int = 200

/*ListAllServicePlansForServiceOK successful response

swagger:response listAllServicePlansForServiceOK
*/
type ListAllServicePlansForServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListAllServicePlansForServiceResponsePaged `json:"body,omitempty"`
}

// NewListAllServicePlansForServiceOK creates ListAllServicePlansForServiceOK with default headers values
func NewListAllServicePlansForServiceOK() *ListAllServicePlansForServiceOK {

	return &ListAllServicePlansForServiceOK{}
}

// WithPayload adds the payload to the list all service plans for service o k response
func (o *ListAllServicePlansForServiceOK) WithPayload(payload *models.ListAllServicePlansForServiceResponsePaged) *ListAllServicePlansForServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all service plans for service o k response
func (o *ListAllServicePlansForServiceOK) SetPayload(payload *models.ListAllServicePlansForServiceResponsePaged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllServicePlansForServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
