#!/bin/bash

function log() {
  echo -e "\e[35mgitea> \e[32m$1\e[39m"
}

public_ip="$1"

if [ -z "${public_ip}" ]; then
  >&2 log "Failed to install gitea: missing public IP"
  exit 1
fi

domain="gitea.${public_ip}.nip.io"
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Installing gitea on public IP ${public_ip}, using domain ${domain}."

helm install gitea "${dir}/chart/gitea" \
  --create-namespace \
  --namespace "gitea" \
  --set "domain=${domain}" >> "$HOME/.carrier.log" 2>&1
