#!/bin/bash

function log() {
  echo -e "\e[35mgitea> \e[32m$1\e[39m"
}

public_ip="$1"
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Installing gitea on public IP ${public_ip}."
template=`cat "$dir/gitea.yaml" | sed "s/{{PUBLIC_IP}}/$public_ip/g"`
echo "$template" | kubectl apply -f - >> "$HOME/.carrier.log"

log "Setting up ingress for gitea."
template=`cat "$dir/ingress.yaml" | sed "s/{{PUBLIC_IP}}/$public_ip/g"`
echo "$template" | kubectl apply -f - >> "$HOME/.carrier.log"

