#!/bin/bash

function log() {
  echo -e "\e[35mgitea> \e[32m$1\e[39m"
}

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Removing gitea."
kubectl delete -f "$dir/gitea.yaml" >> "$HOME/.carrier.log" 2>&1

log "Removing ingress for gitea."
kubectl delete -f "$dir/ingress.yaml" >> "$HOME/.carrier.log" 2>&1
