// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveJobThatWasSuccessfulHandlerFunc turns a function with the right signature into a retrieve job that was successful handler
type RetrieveJobThatWasSuccessfulHandlerFunc func(RetrieveJobThatWasSuccessfulParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveJobThatWasSuccessfulHandlerFunc) Handle(params RetrieveJobThatWasSuccessfulParams) middleware.Responder {
	return fn(params)
}

// RetrieveJobThatWasSuccessfulHandler interface for that can handle valid retrieve job that was successful params
type RetrieveJobThatWasSuccessfulHandler interface {
	Handle(RetrieveJobThatWasSuccessfulParams) middleware.Responder
}

// NewRetrieveJobThatWasSuccessful creates a new http.Handler for the retrieve job that was successful operation
func NewRetrieveJobThatWasSuccessful(ctx *middleware.Context, handler RetrieveJobThatWasSuccessfulHandler) *RetrieveJobThatWasSuccessful {
	return &RetrieveJobThatWasSuccessful{Context: ctx, Handler: handler}
}

/*RetrieveJobThatWasSuccessful swagger:route GET /jobs/{guid} jobs retrieveJobThatWasSuccessful

Retrieve Job that was successful

curl --insecure -i %s/v2/jobs/{guid} -X GET -H 'Authorization: %s'

*/
type RetrieveJobThatWasSuccessful struct {
	Context *middleware.Context
	Handler RetrieveJobThatWasSuccessfulHandler
}

func (o *RetrieveJobThatWasSuccessful) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRetrieveJobThatWasSuccessfulParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
