# Copyright © 2021 - 2023 SUSE LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release Checklist
description: Checklist for a new Epinio release
title: 'Release vX.Y.Z'
labels: ["release"]
body:
  - type: markdown
    attributes:
      value: |
        Checklist and steps to follow for an Epinio release.  
        
        Edit the title with the proper release version number, open the issue and complete the tasks.  

        If you need more details you can find more information in the [Wiki](https://github.com/epinio/epinio/wiki/Releasing-Epinio).  

        ---

  - type: checkboxes
    id: epinio-checklist
    attributes:
      label: Epinio
      options:
        - label: >
            Check the CI status in `epinio/epinio`
            [![CI](https://github.com/epinio/epinio/workflows/CI/badge.svg?branch=main)](https://github.com/epinio/epinio/actions/workflows/main.yml?query=branch%3Amain)
        - label: >
            **( 📝 Manual step )** Tag `epinio` and check the release action.
            [LINK](https://github.com/epinio/epinio/actions/workflows/release.yml)
        - label: >
            Check the release page for the latest assets and changelog.
            [LINK](https://github.com/epinio/epinio/releases)
        - label: >
            Check the `epinio/homebrew-tap` for the latest version.
            [LINK](https://github.com/epinio/homebrew-tap/blob/main/Formula/epinio.rb)
          
  - type: checkboxes
    id: helm-charts-checklist
    attributes:
      label: Helm Charts
      options:
        - label: >
            **( 📝 Manual step )** Check the `epinio/helm-charts` pull requests for the latest updates.
            Ensure that the Epinio UI displays the right Epinio version by setting `epinio-ui.epinioVersion` in `helm-charts/chart/epinio/values.yaml`
            Merge the PR.
            [LINK](https://github.com/epinio/helm-charts/pulls?q=is%3Apr+author%3Aapp%2Fgithub-actions)
        - label: >
            **( 📝 Manual step )** Run the `epinio/helm-charts` release action to publish the latest chart.
            [LINK](https://github.com/epinio/helm-charts/actions/workflows/release.yml)
        - label: >
            **( 📝 Manual step )** Check that the publication of the chart triggered the `epinio/helm-charts`
            epinio docker action to generate a docker image for deploying the latest `epiniod` image.
            [LINK](https://github.com/epinio/helm-charts/actions/workflows/build-epiniod.yml)
            Trigger manually if needed. Check that the resulting docker image is available in `ghcr.io`, with
            the chosen tags [LINK](https://github.com/epinio/helm-charts/pkgs/container/epiniod).

  - type: checkboxes
    id: release-checklist
    attributes:
      label: Release
      options:
        - label: >
            **( 📝 Manual step )** Edit the latest draft release, then publish the release.
            [LINK](https://github.com/epinio/epinio/releases)
        - label: >
            Check the release published action.
            [LINK](https://github.com/epinio/epinio/actions/workflows/release-publish.yml)
        - label: >
            Check that the `Homebrew/homebrew-core` has an open (or already closed) PR with the latest Epinio version.
            [LINK](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+epinio)

  - type: checkboxes
    id: docs-checklist
    attributes:
      label: Docs
      options:
        - label: >
            **( 📝 Manual step )** Check the `epinio/docs` pull requests for the latest update, then merge the PR.
            [LINK](https://github.com/epinio/docs/pulls?q=is:pr+author:app/github-actions)

  - type: checkboxes
    id: others-checklist
    attributes:
      label: Others
      options:
        - label: >
            **( 📝 Manual step )** Docker Extension: check the `epinio/extension-docker-desktop` pull requests for the latest update, then merge the PR.
            [LINK](https://github.com/epinio/extension-docker-desktop/pulls)
            Tag the repository with the next version. [LINK](https://github.com/epinio/extension-docker-desktop/tags)
            Check the result of the action. [LINK](https://github.com/epinio/extension-docker-desktop/actions/workflows/image.yml)
        - label: >
            **( 📝 Manual step )** CIVO marketplace: check the [updatecli action](https://github.com/epinio/kubernetes-marketplace/actions/workflows/updatecli.yml).
            It should have pushed a new branch in the repo. [LINK](https://github.com/epinio/kubernetes-marketplace)
            From this new branch open a PR to the upstream repository. [CIVO Marketplace](https://github.com/civo/kubernetes-marketplace)
        - label: >
            **( 📝 Manual step )** [optional] Rancher marketplace: open a PR in the [Rancher Helm Chart repository](https://github.com/rancher/charts)
