// Code generated by go-swagger; DO NOT EDIT.

package security_group_staging_defaults

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// SetSecurityGroupAsDefaultForStagingOKCode is the HTTP code returned for type SetSecurityGroupAsDefaultForStagingOK
const SetSecurityGroupAsDefaultForStagingOKCode int = 200

/*SetSecurityGroupAsDefaultForStagingOK successful response

swagger:response setSecurityGroupAsDefaultForStagingOK
*/
type SetSecurityGroupAsDefaultForStagingOK struct {

	/*
	  In: Body
	*/
	Payload *models.SetSecurityGroupAsDefaultForStagingResponseResource `json:"body,omitempty"`
}

// NewSetSecurityGroupAsDefaultForStagingOK creates SetSecurityGroupAsDefaultForStagingOK with default headers values
func NewSetSecurityGroupAsDefaultForStagingOK() *SetSecurityGroupAsDefaultForStagingOK {

	return &SetSecurityGroupAsDefaultForStagingOK{}
}

// WithPayload adds the payload to the set security group as default for staging o k response
func (o *SetSecurityGroupAsDefaultForStagingOK) WithPayload(payload *models.SetSecurityGroupAsDefaultForStagingResponseResource) *SetSecurityGroupAsDefaultForStagingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set security group as default for staging o k response
func (o *SetSecurityGroupAsDefaultForStagingOK) SetPayload(payload *models.SetSecurityGroupAsDefaultForStagingResponseResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetSecurityGroupAsDefaultForStagingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
