// Code generated by go-swagger; DO NOT EDIT.

package spaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAllDomainsForSpaceDeprecatedHandlerFunc turns a function with the right signature into a list all domains for space deprecated handler
type ListAllDomainsForSpaceDeprecatedHandlerFunc func(ListAllDomainsForSpaceDeprecatedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllDomainsForSpaceDeprecatedHandlerFunc) Handle(params ListAllDomainsForSpaceDeprecatedParams) middleware.Responder {
	return fn(params)
}

// ListAllDomainsForSpaceDeprecatedHandler interface for that can handle valid list all domains for space deprecated params
type ListAllDomainsForSpaceDeprecatedHandler interface {
	Handle(ListAllDomainsForSpaceDeprecatedParams) middleware.Responder
}

// NewListAllDomainsForSpaceDeprecated creates a new http.Handler for the list all domains for space deprecated operation
func NewListAllDomainsForSpaceDeprecated(ctx *middleware.Context, handler ListAllDomainsForSpaceDeprecatedHandler) *ListAllDomainsForSpaceDeprecated {
	return &ListAllDomainsForSpaceDeprecated{Context: ctx, Handler: handler}
}

/*ListAllDomainsForSpaceDeprecated swagger:route GET /spaces/{guid}/domains spaces listAllDomainsForSpaceDeprecated

List all Domains for the Space (deprecated)

curl --insecure -i %s/v2/spaces/{guid}/domains -X GET -H 'Authorization: %s'

*/
type ListAllDomainsForSpaceDeprecated struct {
	Context *middleware.Context
	Handler ListAllDomainsForSpaceDeprecatedHandler
}

func (o *ListAllDomainsForSpaceDeprecated) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllDomainsForSpaceDeprecatedParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
