// Code generated by go-swagger; DO NOT EDIT.

package spaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAllManagersForSpaceHandlerFunc turns a function with the right signature into a list all managers for space handler
type ListAllManagersForSpaceHandlerFunc func(ListAllManagersForSpaceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllManagersForSpaceHandlerFunc) Handle(params ListAllManagersForSpaceParams) middleware.Responder {
	return fn(params)
}

// ListAllManagersForSpaceHandler interface for that can handle valid list all managers for space params
type ListAllManagersForSpaceHandler interface {
	Handle(ListAllManagersForSpaceParams) middleware.Responder
}

// NewListAllManagersForSpace creates a new http.Handler for the list all managers for space operation
func NewListAllManagersForSpace(ctx *middleware.Context, handler ListAllManagersForSpaceHandler) *ListAllManagersForSpace {
	return &ListAllManagersForSpace{Context: ctx, Handler: handler}
}

/*ListAllManagersForSpace swagger:route GET /spaces/{guid}/managers spaces listAllManagersForSpace

List all Managers for the Space

curl --insecure -i %s/v2/spaces/{guid}/managers -X GET -H 'Authorization: %s'

*/
type ListAllManagersForSpace struct {
	Context *middleware.Context
	Handler ListAllManagersForSpaceHandler
}

func (o *ListAllManagersForSpace) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllManagersForSpaceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
