// Code generated by go-swagger; DO NOT EDIT.

package spaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveSpaceHandlerFunc turns a function with the right signature into a retrieve space handler
type RetrieveSpaceHandlerFunc func(RetrieveSpaceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveSpaceHandlerFunc) Handle(params RetrieveSpaceParams) middleware.Responder {
	return fn(params)
}

// RetrieveSpaceHandler interface for that can handle valid retrieve space params
type RetrieveSpaceHandler interface {
	Handle(RetrieveSpaceParams) middleware.Responder
}

// NewRetrieveSpace creates a new http.Handler for the retrieve space operation
func NewRetrieveSpace(ctx *middleware.Context, handler RetrieveSpaceHandler) *RetrieveSpace {
	return &RetrieveSpace{Context: ctx, Handler: handler}
}

/*RetrieveSpace swagger:route GET /spaces/{guid} spaces retrieveSpace

Retrieve a Particular Space

curl --insecure -i %s/v2/spaces/{guid} -X GET -H 'Authorization: %s'

*/
type RetrieveSpace struct {
	Context *middleware.Context
	Handler RetrieveSpaceHandler
}

func (o *RetrieveSpace) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRetrieveSpaceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
