#!/bin/bash

function log() {
  echo -e "\e[35mquarks> \e[32m$1\e[39m"
}

log "Adding quarks repo to helm."
helm repo add quarks https://cloudfoundry-incubator.github.io/quarks-helm/ >> "$HOME/.carrier.log"

log "Creating quarks namespace."
kubectl create namespace quarks >> "$HOME/.carrier.log"

log "Installing quarks."
helm install quarks-operator quarks/cf-operator --version 6.1.17+0.gec409fd7 -n quarks >> "$HOME/.carrier.log"
