#!/bin/bash

function log() {
  echo -e "\e[35mquarks> \e[32m$1\e[39m"
}

log "Removing quarks."
helm uninstall quarks-secret -n quarks >> "$HOME/.carrier.log" 2>&1

log "Deleting quarks namespace."
kubectl delete namespace quarks >> "$HOME/.carrier.log" 2>&1

