// Code generated by go-swagger; DO NOT EDIT.

package service_plan_visibilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteServicePlanVisibilitiesNoContentCode is the HTTP code returned for type DeleteServicePlanVisibilitiesNoContent
const DeleteServicePlanVisibilitiesNoContentCode int = 204

/*DeleteServicePlanVisibilitiesNoContent successful response

swagger:response deleteServicePlanVisibilitiesNoContent
*/
type DeleteServicePlanVisibilitiesNoContent struct {
}

// NewDeleteServicePlanVisibilitiesNoContent creates DeleteServicePlanVisibilitiesNoContent with default headers values
func NewDeleteServicePlanVisibilitiesNoContent() *DeleteServicePlanVisibilitiesNoContent {

	return &DeleteServicePlanVisibilitiesNoContent{}
}

// WriteResponse to the client
func (o *DeleteServicePlanVisibilitiesNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
