// Code generated by go-swagger; DO NOT EDIT.

package service_plan_visibilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// UpdateServicePlanVisibilityCreatedCode is the HTTP code returned for type UpdateServicePlanVisibilityCreated
const UpdateServicePlanVisibilityCreatedCode int = 201

/*UpdateServicePlanVisibilityCreated successful response

swagger:response updateServicePlanVisibilityCreated
*/
type UpdateServicePlanVisibilityCreated struct {

	/*
	  In: Body
	*/
	Payload *models.UpdateServicePlanVisibilityResponseResource `json:"body,omitempty"`
}

// NewUpdateServicePlanVisibilityCreated creates UpdateServicePlanVisibilityCreated with default headers values
func NewUpdateServicePlanVisibilityCreated() *UpdateServicePlanVisibilityCreated {

	return &UpdateServicePlanVisibilityCreated{}
}

// WithPayload adds the payload to the update service plan visibility created response
func (o *UpdateServicePlanVisibilityCreated) WithPayload(payload *models.UpdateServicePlanVisibilityResponseResource) *UpdateServicePlanVisibilityCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update service plan visibility created response
func (o *UpdateServicePlanVisibilityCreated) SetPayload(payload *models.UpdateServicePlanVisibilityResponseResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateServicePlanVisibilityCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
