// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteStackNoContentCode is the HTTP code returned for type DeleteStackNoContent
const DeleteStackNoContentCode int = 204

/*DeleteStackNoContent successful response

swagger:response deleteStackNoContent
*/
type DeleteStackNoContent struct {
}

// NewDeleteStackNoContent creates DeleteStackNoContent with default headers values
func NewDeleteStackNoContent() *DeleteStackNoContent {

	return &DeleteStackNoContent{}
}

// WriteResponse to the client
func (o *DeleteStackNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
