---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex-server
  namespace: dex

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dex-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-server-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex-server
subjects:
- kind: ServiceAccount
  name: dex-server
  namespace: dex

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: dex-server
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: "##dex_version##"
  name: dex-server
  namespace: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: dex-server
      app.kubernetes.io/part-of: epinio
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dex-server
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: dex-server
        app.kubernetes.io/part-of: epinio
        app.kubernetes.io/version: "##dex_version##"
      name: dex-server
    spec:
      serviceAccountName: dex-server
      containers:
        - command: ["/dex", "serve"]
          # TODO: Create a configmap for this config and mount it as a volume
          args: ["/config/dex.yaml"]
          image: ghcr.io/dexidp/dex:v2.29.0
          livenessProbe:
            httpGet:
              path: /dex/auth
              port: 5556
          readinessProbe:
            httpGet:
              path: /dex/auth
              port: 5556
          name: dex-server
          ports:
            - containerPort: 5556

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: dex
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: dex-server
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: "##dex_version##"
  name: dex-server
  namespace: dex
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 556
  selector:
    app.kubernetes.io/name: dex-server
