// Copyright © 2021 - 2023 SUSE LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by counterfeiter. DO NOT EDIT.
package cmdfakes

import (
	"sync"

	"github.com/epinio/epinio/internal/cli/cmd"
	"github.com/epinio/epinio/internal/cli/usercmd"
)

type FakeNamespaceMatcher struct {
	GetAPIStub        func() usercmd.APIClient
	getAPIMutex       sync.RWMutex
	getAPIArgsForCall []struct {
	}
	getAPIReturns struct {
		result1 usercmd.APIClient
	}
	getAPIReturnsOnCall map[int]struct {
		result1 usercmd.APIClient
	}
	NamespacesMatchingStub        func(string) []string
	namespacesMatchingMutex       sync.RWMutex
	namespacesMatchingArgsForCall []struct {
		arg1 string
	}
	namespacesMatchingReturns struct {
		result1 []string
	}
	namespacesMatchingReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNamespaceMatcher) GetAPI() usercmd.APIClient {
	fake.getAPIMutex.Lock()
	ret, specificReturn := fake.getAPIReturnsOnCall[len(fake.getAPIArgsForCall)]
	fake.getAPIArgsForCall = append(fake.getAPIArgsForCall, struct {
	}{})
	stub := fake.GetAPIStub
	fakeReturns := fake.getAPIReturns
	fake.recordInvocation("GetAPI", []interface{}{})
	fake.getAPIMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNamespaceMatcher) GetAPICallCount() int {
	fake.getAPIMutex.RLock()
	defer fake.getAPIMutex.RUnlock()
	return len(fake.getAPIArgsForCall)
}

func (fake *FakeNamespaceMatcher) GetAPICalls(stub func() usercmd.APIClient) {
	fake.getAPIMutex.Lock()
	defer fake.getAPIMutex.Unlock()
	fake.GetAPIStub = stub
}

func (fake *FakeNamespaceMatcher) GetAPIReturns(result1 usercmd.APIClient) {
	fake.getAPIMutex.Lock()
	defer fake.getAPIMutex.Unlock()
	fake.GetAPIStub = nil
	fake.getAPIReturns = struct {
		result1 usercmd.APIClient
	}{result1}
}

func (fake *FakeNamespaceMatcher) GetAPIReturnsOnCall(i int, result1 usercmd.APIClient) {
	fake.getAPIMutex.Lock()
	defer fake.getAPIMutex.Unlock()
	fake.GetAPIStub = nil
	if fake.getAPIReturnsOnCall == nil {
		fake.getAPIReturnsOnCall = make(map[int]struct {
			result1 usercmd.APIClient
		})
	}
	fake.getAPIReturnsOnCall[i] = struct {
		result1 usercmd.APIClient
	}{result1}
}

func (fake *FakeNamespaceMatcher) NamespacesMatching(arg1 string) []string {
	fake.namespacesMatchingMutex.Lock()
	ret, specificReturn := fake.namespacesMatchingReturnsOnCall[len(fake.namespacesMatchingArgsForCall)]
	fake.namespacesMatchingArgsForCall = append(fake.namespacesMatchingArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.NamespacesMatchingStub
	fakeReturns := fake.namespacesMatchingReturns
	fake.recordInvocation("NamespacesMatching", []interface{}{arg1})
	fake.namespacesMatchingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNamespaceMatcher) NamespacesMatchingCallCount() int {
	fake.namespacesMatchingMutex.RLock()
	defer fake.namespacesMatchingMutex.RUnlock()
	return len(fake.namespacesMatchingArgsForCall)
}

func (fake *FakeNamespaceMatcher) NamespacesMatchingCalls(stub func(string) []string) {
	fake.namespacesMatchingMutex.Lock()
	defer fake.namespacesMatchingMutex.Unlock()
	fake.NamespacesMatchingStub = stub
}

func (fake *FakeNamespaceMatcher) NamespacesMatchingArgsForCall(i int) string {
	fake.namespacesMatchingMutex.RLock()
	defer fake.namespacesMatchingMutex.RUnlock()
	argsForCall := fake.namespacesMatchingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeNamespaceMatcher) NamespacesMatchingReturns(result1 []string) {
	fake.namespacesMatchingMutex.Lock()
	defer fake.namespacesMatchingMutex.Unlock()
	fake.NamespacesMatchingStub = nil
	fake.namespacesMatchingReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeNamespaceMatcher) NamespacesMatchingReturnsOnCall(i int, result1 []string) {
	fake.namespacesMatchingMutex.Lock()
	defer fake.namespacesMatchingMutex.Unlock()
	fake.NamespacesMatchingStub = nil
	if fake.namespacesMatchingReturnsOnCall == nil {
		fake.namespacesMatchingReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.namespacesMatchingReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeNamespaceMatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAPIMutex.RLock()
	defer fake.getAPIMutex.RUnlock()
	fake.namespacesMatchingMutex.RLock()
	defer fake.namespacesMatchingMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNamespaceMatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cmd.NamespaceMatcher = new(FakeNamespaceMatcher)
