// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AssociateManagedOrganizationWithUserHandlerFunc turns a function with the right signature into a associate managed organization with user handler
type AssociateManagedOrganizationWithUserHandlerFunc func(AssociateManagedOrganizationWithUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AssociateManagedOrganizationWithUserHandlerFunc) Handle(params AssociateManagedOrganizationWithUserParams) middleware.Responder {
	return fn(params)
}

// AssociateManagedOrganizationWithUserHandler interface for that can handle valid associate managed organization with user params
type AssociateManagedOrganizationWithUserHandler interface {
	Handle(AssociateManagedOrganizationWithUserParams) middleware.Responder
}

// NewAssociateManagedOrganizationWithUser creates a new http.Handler for the associate managed organization with user operation
func NewAssociateManagedOrganizationWithUser(ctx *middleware.Context, handler AssociateManagedOrganizationWithUserHandler) *AssociateManagedOrganizationWithUser {
	return &AssociateManagedOrganizationWithUser{Context: ctx, Handler: handler}
}

/*AssociateManagedOrganizationWithUser swagger:route PUT /users/{guid}/managed_organizations/{managed_organization_guid} users associateManagedOrganizationWithUser

Associate Managed Organization with the User

curl --insecure -i %s/v2/users/{guid}/managed_organizations/{managed_organization_guid} -X PUT -H 'Authorization: %s'

*/
type AssociateManagedOrganizationWithUser struct {
	Context *middleware.Context
	Handler AssociateManagedOrganizationWithUserHandler
}

func (o *AssociateManagedOrganizationWithUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAssociateManagedOrganizationWithUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
