// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RemoveSpaceFromUserHandlerFunc turns a function with the right signature into a remove space from user handler
type RemoveSpaceFromUserHandlerFunc func(RemoveSpaceFromUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveSpaceFromUserHandlerFunc) Handle(params RemoveSpaceFromUserParams) middleware.Responder {
	return fn(params)
}

// RemoveSpaceFromUserHandler interface for that can handle valid remove space from user params
type RemoveSpaceFromUserHandler interface {
	Handle(RemoveSpaceFromUserParams) middleware.Responder
}

// NewRemoveSpaceFromUser creates a new http.Handler for the remove space from user operation
func NewRemoveSpaceFromUser(ctx *middleware.Context, handler RemoveSpaceFromUserHandler) *RemoveSpaceFromUser {
	return &RemoveSpaceFromUser{Context: ctx, Handler: handler}
}

/*RemoveSpaceFromUser swagger:route DELETE /users/{guid}/spaces/{space_guid} users removeSpaceFromUser

Remove Space from the User

curl --insecure -i %s/v2/users/{guid}/spaces/{space_guid} -X DELETE -H 'Authorization: %s'

*/
type RemoveSpaceFromUser struct {
	Context *middleware.Context
	Handler RemoveSpaceFromUserHandler
}

func (o *RemoveSpaceFromUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveSpaceFromUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
