// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RemoveBillingManagedOrganizationFromUserHandlerFunc turns a function with the right signature into a remove billing managed organization from user handler
type RemoveBillingManagedOrganizationFromUserHandlerFunc func(RemoveBillingManagedOrganizationFromUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveBillingManagedOrganizationFromUserHandlerFunc) Handle(params RemoveBillingManagedOrganizationFromUserParams) middleware.Responder {
	return fn(params)
}

// RemoveBillingManagedOrganizationFromUserHandler interface for that can handle valid remove billing managed organization from user params
type RemoveBillingManagedOrganizationFromUserHandler interface {
	Handle(RemoveBillingManagedOrganizationFromUserParams) middleware.Responder
}

// NewRemoveBillingManagedOrganizationFromUser creates a new http.Handler for the remove billing managed organization from user operation
func NewRemoveBillingManagedOrganizationFromUser(ctx *middleware.Context, handler RemoveBillingManagedOrganizationFromUserHandler) *RemoveBillingManagedOrganizationFromUser {
	return &RemoveBillingManagedOrganizationFromUser{Context: ctx, Handler: handler}
}

/*RemoveBillingManagedOrganizationFromUser swagger:route DELETE /users/{guid}/billing_managed_organizations/{billing_managed_organization_guid} users removeBillingManagedOrganizationFromUser

Remove Billing Managed Organization from the User

curl --insecure -i %s/v2/users/{guid}/billing_managed_organizations/{billing_managed_organization_guid} -X DELETE -H 'Authorization: %s'

*/
type RemoveBillingManagedOrganizationFromUser struct {
	Context *middleware.Context
	Handler RemoveBillingManagedOrganizationFromUserHandler
}

func (o *RemoveBillingManagedOrganizationFromUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveBillingManagedOrganizationFromUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
