// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// RemoveSpaceFromUserCreatedCode is the HTTP code returned for type RemoveSpaceFromUserCreated
const RemoveSpaceFromUserCreatedCode int = 201

/*RemoveSpaceFromUserCreated successful response

swagger:response removeSpaceFromUserCreated
*/
type RemoveSpaceFromUserCreated struct {

	/*
	  In: Body
	*/
	Payload *models.RemoveSpaceFromUserResponse `json:"body,omitempty"`
}

// NewRemoveSpaceFromUserCreated creates RemoveSpaceFromUserCreated with default headers values
func NewRemoveSpaceFromUserCreated() *RemoveSpaceFromUserCreated {

	return &RemoveSpaceFromUserCreated{}
}

// WithPayload adds the payload to the remove space from user created response
func (o *RemoveSpaceFromUserCreated) WithPayload(payload *models.RemoveSpaceFromUserResponse) *RemoveSpaceFromUserCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove space from user created response
func (o *RemoveSpaceFromUserCreated) SetPayload(payload *models.RemoveSpaceFromUserResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveSpaceFromUserCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
