// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// PostOauthTokenOKCode is the HTTP code returned for type PostOauthTokenOK
const PostOauthTokenOKCode int = 200

/*PostOauthTokenOK successful response

swagger:response postOauthTokenOK
*/
type PostOauthTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.CreatesOAuthTokenResponse `json:"body,omitempty"`
}

// NewPostOauthTokenOK creates PostOauthTokenOK with default headers values
func NewPostOauthTokenOK() *PostOauthTokenOK {

	return &PostOauthTokenOK{}
}

// WithPayload adds the payload to the post oauth token o k response
func (o *PostOauthTokenOK) WithPayload(payload *models.CreatesOAuthTokenResponse) *PostOauthTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post oauth token o k response
func (o *PostOauthTokenOK) SetPayload(payload *models.CreatesOAuthTokenResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOauthTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
