// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CopyAppBitsForAppRequest copy app bits for app request
//
// swagger:model copyAppBitsForAppRequest
type CopyAppBitsForAppRequest struct {

	// The guid for the source app
	SourceAppGUID string `json:"source_app_guid,omitempty"`
}

// Validate validates this copy app bits for app request
func (m *CopyAppBitsForAppRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CopyAppBitsForAppRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CopyAppBitsForAppRequest) UnmarshalBinary(b []byte) error {
	var res CopyAppBitsForAppRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
