// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateSharedDomainResponse create shared domain response
//
// swagger:model createSharedDomainResponse
type CreateSharedDomainResponse struct {

	// The name
	Name string `json:"name,omitempty"`
}

// Validate validates this create shared domain response
func (m *CreateSharedDomainResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSharedDomainResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSharedDomainResponse) UnmarshalBinary(b []byte) error {
	var res CreateSharedDomainResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
