// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetOrganizationSummaryResponse get organization summary response
//
// swagger:model getOrganizationSummaryResponse
type GetOrganizationSummaryResponse struct {

	// The guid
	GUID string `json:"guid,omitempty"`

	// The name
	Name string `json:"name,omitempty"`

	// The spaces
	Spaces []GenericObject `json:"spaces"`

	// The status
	Status string `json:"status,omitempty"`
}

// Validate validates this get organization summary response
func (m *GetOrganizationSummaryResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSpaces(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetOrganizationSummaryResponse) validateSpaces(formats strfmt.Registry) error {

	if swag.IsZero(m.Spaces) { // not required
		return nil
	}

	for i := 0; i < len(m.Spaces); i++ {

		if err := m.Spaces[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("spaces" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetOrganizationSummaryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetOrganizationSummaryResponse) UnmarshalBinary(b []byte) error {
	var res GetOrganizationSummaryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
