// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListAllPrivateDomainsForOrganizationResponse list all private domains for organization response
//
// swagger:model listAllPrivateDomainsForOrganizationResponse
type ListAllPrivateDomainsForOrganizationResponse struct {

	// The name
	Name string `json:"name,omitempty"`

	// The owning Organization Guid
	OwningOrganizationGUID string `json:"owning_organization_guid,omitempty"`

	// The owning Organization Url
	OwningOrganizationURL string `json:"owning_organization_url,omitempty"`
}

// Validate validates this list all private domains for organization response
func (m *ListAllPrivateDomainsForOrganizationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListAllPrivateDomainsForOrganizationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListAllPrivateDomainsForOrganizationResponse) UnmarshalBinary(b []byte) error {
	var res ListAllPrivateDomainsForOrganizationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
