// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MigrateServiceInstancesFromOneServicePlanToAnotherServicePlanExperimentalResponse migrate service instances from one service plan to another service plan experimental response
//
// swagger:model migrateServiceInstancesFromOneServicePlanToAnotherServicePlanExperimentalResponse
type MigrateServiceInstancesFromOneServicePlanToAnotherServicePlanExperimentalResponse struct {

	// The changed Count
	ChangedCount int64 `json:"changed_count,omitempty"`
}

// Validate validates this migrate service instances from one service plan to another service plan experimental response
func (m *MigrateServiceInstancesFromOneServicePlanToAnotherServicePlanExperimentalResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MigrateServiceInstancesFromOneServicePlanToAnotherServicePlanExperimentalResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MigrateServiceInstancesFromOneServicePlanToAnotherServicePlanExperimentalResponse) UnmarshalBinary(b []byte) error {
	var res MigrateServiceInstancesFromOneServicePlanToAnotherServicePlanExperimentalResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
