// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RemoveSpaceFromSpaceQuotaDefinitionResponse remove space from space quota definition response
//
// swagger:model removeSpaceFromSpaceQuotaDefinitionResponse
type RemoveSpaceFromSpaceQuotaDefinitionResponse struct {

	// The instance Memory Limit
	InstanceMemoryLimit int64 `json:"instance_memory_limit,omitempty"`

	// The memory Limit
	MemoryLimit int64 `json:"memory_limit,omitempty"`

	// The name
	Name string `json:"name,omitempty"`

	// The non Basic Services Allowed
	NonBasicServicesAllowed bool `json:"non_basic_services_allowed,omitempty"`

	// The organization Guid
	OrganizationGUID string `json:"organization_guid,omitempty"`

	// The organization Url
	OrganizationURL string `json:"organization_url,omitempty"`

	// The spaces Url
	SpacesURL string `json:"spaces_url,omitempty"`

	// The total Routes
	TotalRoutes int64 `json:"total_routes,omitempty"`

	// The total Services
	TotalServices int64 `json:"total_services,omitempty"`
}

// Validate validates this remove space from space quota definition response
func (m *RemoveSpaceFromSpaceQuotaDefinitionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RemoveSpaceFromSpaceQuotaDefinitionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoveSpaceFromSpaceQuotaDefinitionResponse) UnmarshalBinary(b []byte) error {
	var res RemoveSpaceFromSpaceQuotaDefinitionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
