// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RetrieveJobThatIsQueuedResponse retrieve job that is queued response
//
// swagger:model retrieveJobThatIsQueuedResponse
type RetrieveJobThatIsQueuedResponse struct {

	// The guid
	GUID string `json:"guid,omitempty"`

	// The status
	Status string `json:"status,omitempty"`
}

// Validate validates this retrieve job that is queued response
func (m *RetrieveJobThatIsQueuedResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetrieveJobThatIsQueuedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetrieveJobThatIsQueuedResponse) UnmarshalBinary(b []byte) error {
	var res RetrieveJobThatIsQueuedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
