// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RetrievingPermissionsOnServiceInstanceResponse retrieving permissions on service instance response
//
// swagger:model retrievingPermissionsOnServiceInstanceResponse
type RetrievingPermissionsOnServiceInstanceResponse struct {

	// The manage
	Manage bool `json:"manage,omitempty"`
}

// Validate validates this retrieving permissions on service instance response
func (m *RetrievingPermissionsOnServiceInstanceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetrievingPermissionsOnServiceInstanceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetrievingPermissionsOnServiceInstanceResponse) UnmarshalBinary(b []byte) error {
	var res RetrievingPermissionsOnServiceInstanceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
