// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RetrievingOrganizationMemoryUsageResponse retrieving organization memory usage response
//
// swagger:model retrievingOrganizationMemoryUsageResponse
type RetrievingOrganizationMemoryUsageResponse struct {

	// The memory Usage In Mb
	MemoryUsageInMb int64 `json:"memory_usage_in_mb,omitempty"`
}

// Validate validates this retrieving organization memory usage response
func (m *RetrievingOrganizationMemoryUsageResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetrievingOrganizationMemoryUsageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetrievingOrganizationMemoryUsageResponse) UnmarshalBinary(b []byte) error {
	var res RetrievingOrganizationMemoryUsageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
