// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SetFeatureFlagRequest set feature flag request
//
// swagger:model setFeatureFlagRequest
type SetFeatureFlagRequest struct {

	// The state of the feature flag.
	Enabled bool `json:"enabled,omitempty"`

	// The custom error message for the feature flag.
	ErrorMessage string `json:"error_message,omitempty"`
}

// Validate validates this set feature flag request
func (m *SetFeatureFlagRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SetFeatureFlagRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetFeatureFlagRequest) UnmarshalBinary(b []byte) error {
	var res SetFeatureFlagRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
