// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateContentsOfRunningEnvironmentVariableGroupRequest update contents of running environment variable group request
//
// swagger:model updateContentsOfRunningEnvironmentVariableGroupRequest
type UpdateContentsOfRunningEnvironmentVariableGroupRequest struct {

	// The abc
	Abc int64 `json:"abc,omitempty"`

	// The doreme
	DoReMe string `json:"do-re-me,omitempty"`
}

// Validate validates this update contents of running environment variable group request
func (m *UpdateContentsOfRunningEnvironmentVariableGroupRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateContentsOfRunningEnvironmentVariableGroupRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateContentsOfRunningEnvironmentVariableGroupRequest) UnmarshalBinary(b []byte) error {
	var res UpdateContentsOfRunningEnvironmentVariableGroupRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
