#!/bin/bash

function log() {
  echo -e "\e[35mkpack> \e[32m$1\e[39m"
}

username="$1"
password="$2"
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

config_json=`echo -n "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$username\",\"password\":\"$password\"}}}" | base64 -w 0`

log "Setting up dockerhub credentials for kpack."
template=`cat "$dir/dockerhub-creds.yaml" | sed -e "s/{{CONFIG_JSON}}/$config_json/g"`
echo -n "$template" | kubectl apply -f - >> "$HOME/.carrier.log"

log "Creating a service account for kpack."
kubectl apply -f "$dir/service-account.yaml" >> "$HOME/.carrier.log"

log "Installing kpack."
kubectl apply -f "$dir/release-0.1.2.yaml" >> "$HOME/.carrier.log"

log "Waiting for webhook to come online."
retry 60 'kubectl wait --for=condition=Ready --timeout=5s -n kpack --selector=app=kpack-webhook pod' >> "$HOME/.carrier.log" 2>&1

log "Setting up a kpack store."
kubectl apply -f "$dir/store.yaml" >> "$HOME/.carrier.log"

log "Setting up a kpack stack."
kubectl apply -f "$dir/stack.yaml" >> "$HOME/.carrier.log"

log "Creating a kpack builder."
kubectl apply -f "$dir/builder.yaml" >> "$HOME/.carrier.log"
