#!/bin/bash

function log() {
  echo -e "\e[35mingress> \e[32m$1\e[39m"
}

log "Creating cluster role binding for the nginx ingress."
kubectl create clusterrolebinding cluster-admin-binding \
  --clusterrole cluster-admin \
  --user $(gcloud config get-value account) >> "$HOME/.carrier.log"

log "Installing nginx ingress."
kubectl apply -f \
  https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.40.2/deploy/static/provider/cloud/deploy.yaml \
  >> "$HOME/.carrier.log"
