#!/bin/bash

function log() {
  echo -e "\e[35mingress> \e[32m$1\e[39m"
}

log "Removing cluster role binding for the nginx ingress."
kubectl delete clusterrolebinding cluster-admin-binding >> "$HOME/.carrier.log" 2>&1

log "Removing nginx installation."
kubectl delete -f \
  https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.40.2/deploy/static/provider/cloud/deploy.yaml \
  >> "$HOME/.carrier.log" 2>&1
