#!/bin/bash

function log() {
  echo -e "\e[35mingress> \e[90m$1\e[39m"
}

log "Waiting for ingress to come online ..."
retry 60 'kubectl wait --for=condition=Ready --timeout=5s -n ingress-nginx --selector=app.kubernetes.io/component=controller pod' >> "$HOME/.carrier.log" 2>&1

log "Waiting for load balancer IP address to be allocated ..."
retry 60 'kubectl get svc -n ingress-nginx  ingress-nginx-controller -o json | jq -r .status.loadBalancer.ingress[0].ip | grep -q "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*"'
