// Code generated by go-swagger; DO NOT EDIT.

package domains_deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/suse/carrier/shim/models"
)

// NewCreatesDomainOwnedByGivenOrganizationDeprecatedParams creates a new CreatesDomainOwnedByGivenOrganizationDeprecatedParams object
// no default values defined in spec.
func NewCreatesDomainOwnedByGivenOrganizationDeprecatedParams() CreatesDomainOwnedByGivenOrganizationDeprecatedParams {

	return CreatesDomainOwnedByGivenOrganizationDeprecatedParams{}
}

// CreatesDomainOwnedByGivenOrganizationDeprecatedParams contains all the bound params for the creates domain owned by given organization deprecated operation
// typically these are obtained from a http.Request
//
// swagger:parameters createsDomainOwnedByGivenOrganizationDeprecated
type CreatesDomainOwnedByGivenOrganizationDeprecatedParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*An object instance that is serialized and sent as the request body.
	  Required: true
	  In: body
	*/
	Value *models.CreatesDomainOwnedByGivenOrganizationDeprecatedRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreatesDomainOwnedByGivenOrganizationDeprecatedParams() beforehand.
func (o *CreatesDomainOwnedByGivenOrganizationDeprecatedParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CreatesDomainOwnedByGivenOrganizationDeprecatedRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("value", "body", ""))
			} else {
				res = append(res, errors.NewParseError("value", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Value = &body
			}
		}
	} else {
		res = append(res, errors.Required("value", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
