#!/bin/bash

function log() {
  echo -e "\e[35margo> \e[32m$1\e[39m"
}

public_ip="$1"

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Waiting for gitea to come online."
retry 60 'kubectl wait --for=condition=Ready --timeout=5s -n gitea --selector=app=gitea pod' >> "$HOME/.carrier.log" 2>&1
retry 60 "curl --fail http://gitea.$public_ip.nip.io" >> "$HOME/.carrier.log" 2>&1

# log "Setting up a gitea app."
# app_token=$(curl -sb -X POST "http://dev:changeme@gitea.$public_ip.nip.io/api/v1/user/applications/oauth2" \
#                 -H "accept: application/json" \
#                 -H "Content-Type: application/json" \
#                 -d "{  \"name\": \"drone\",  \"redirect_uris\": [\"http://drone.$public_ip.nip.io/login\" ]}")
# app_client=$(echo $app_token | jq -r .client_id)
# app_secret=$(echo $app_token | jq -r .client_secret)

log "Creating argo namespace."
kubectl create namespace argo >> "$HOME/.carrier.log" 2>&1

log "Installing argo."
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml >> "$HOME/.carrier.log" 2>&1
