// Code generated by go-swagger; DO NOT EDIT.

package app_usage_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/suse/carrier/shim/models"
)

// ListAllAppUsageEventsOKCode is the HTTP code returned for type ListAllAppUsageEventsOK
const ListAllAppUsageEventsOKCode int = 200

/*ListAllAppUsageEventsOK successful response

swagger:response listAllAppUsageEventsOK
*/
type ListAllAppUsageEventsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListAllAppUsageEventsResponsePaged `json:"body,omitempty"`
}

// NewListAllAppUsageEventsOK creates ListAllAppUsageEventsOK with default headers values
func NewListAllAppUsageEventsOK() *ListAllAppUsageEventsOK {

	return &ListAllAppUsageEventsOK{}
}

// WithPayload adds the payload to the list all app usage events o k response
func (o *ListAllAppUsageEventsOK) WithPayload(payload *models.ListAllAppUsageEventsResponsePaged) *ListAllAppUsageEventsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all app usage events o k response
func (o *ListAllAppUsageEventsOK) SetPayload(payload *models.ListAllAppUsageEventsResponsePaged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllAppUsageEventsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
