apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:                                                                                                                                       
    - "--serversTransport.insecureSkipVerify=true"
    - "--entrypoints.websecure.http.tls.certresolver=default"
    - "--entrypoints.websecure.http.tls.domains[0].main=sslip.io"
    - "--entrypoints.websecure.http.tls.domains[0].sans=epinio.172.18.0.3.sslip.io"

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epinio-tls
  namespace: epinio
spec:
  dnsNames:
  - 'epinio.172.18.0.3.sslip.io'
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  secretName: epinio-tls