// Code generated by go-swagger; DO NOT EDIT.

package service_plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAllServicePlansHandlerFunc turns a function with the right signature into a list all service plans handler
type ListAllServicePlansHandlerFunc func(ListAllServicePlansParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllServicePlansHandlerFunc) Handle(params ListAllServicePlansParams) middleware.Responder {
	return fn(params)
}

// ListAllServicePlansHandler interface for that can handle valid list all service plans params
type ListAllServicePlansHandler interface {
	Handle(ListAllServicePlansParams) middleware.Responder
}

// NewListAllServicePlans creates a new http.Handler for the list all service plans operation
func NewListAllServicePlans(ctx *middleware.Context, handler ListAllServicePlansHandler) *ListAllServicePlans {
	return &ListAllServicePlans{Context: ctx, Handler: handler}
}

/*ListAllServicePlans swagger:route GET /service_plans servicePlans listAllServicePlans

List all Service Plans

curl --insecure -i %s/v2/service_plans -X GET -H 'Authorization: %s'

*/
type ListAllServicePlans struct {
	Context *middleware.Context
	Handler ListAllServicePlansHandler
}

func (o *ListAllServicePlans) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllServicePlansParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
