#!/bin/bash

function log() {
  echo -e "\e[35mregistry> \e[32m$1\e[39m"
}

public_ip="$1"

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Creating registry namespace."
kubectl create namespace carrier-registry >> "$HOME/.carrier.log"

log "Labeling registry namespace."
kubectl label namespace carrier-registry quarks.cloudfoundry.org/monitored=quarks-secret >> "$HOME/.carrier.log"

log "Installing registry."
helm install carrier-registry "${dir}/chart/container-registry" \
  --namespace "carrier-registry" >> "$HOME/.carrier.log" 2>&1
