#!/bin/bash

function log() {
  echo -e "\e[35mregistry> \e[32m$1\e[39m"
}

public_ip="$1"

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Uninstalling registry."
helm uninstall carrier-registry "${dir}/chart/container-registry" \
  --namespace "carrier-registry" >> "$HOME/.carrier.log" 2>&1

log "Removing registry namespace."
kubectl delete namespace carrier-registry >> "$HOME/.carrier.log" 2>&1
