// Code generated by go-swagger; DO NOT EDIT.

package shared_domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSharedDomainHandlerFunc turns a function with the right signature into a delete shared domain handler
type DeleteSharedDomainHandlerFunc func(DeleteSharedDomainParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSharedDomainHandlerFunc) Handle(params DeleteSharedDomainParams) middleware.Responder {
	return fn(params)
}

// DeleteSharedDomainHandler interface for that can handle valid delete shared domain params
type DeleteSharedDomainHandler interface {
	Handle(DeleteSharedDomainParams) middleware.Responder
}

// NewDeleteSharedDomain creates a new http.Handler for the delete shared domain operation
func NewDeleteSharedDomain(ctx *middleware.Context, handler DeleteSharedDomainHandler) *DeleteSharedDomain {
	return &DeleteSharedDomain{Context: ctx, Handler: handler}
}

/*DeleteSharedDomain swagger:route DELETE /shared_domains/{guid} sharedDomains deleteSharedDomain

Delete a Particular Shared Domain

curl --insecure -i %s/v2/shared_domains/{guid} -X DELETE -H 'Authorization: %s'

*/
type DeleteSharedDomain struct {
	Context *middleware.Context
	Handler DeleteSharedDomainHandler
}

func (o *DeleteSharedDomain) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteSharedDomainParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
