#!/bin/bash

function log() {
  echo -e "\e[35mbrigade> \e[32m$1\e[39m"
}

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Removing brigade."
helm delete brigade-server --namespace brigade >> "$HOME/.carrier.log" 2>&1

log "Deleting brigade namespace."
kubectl delete namespace brigade >> "$HOME/.carrier.log" 2>&1
