// Code generated by go-swagger; DO NOT EDIT.

package buildpacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreatesAdminBuildpackHandlerFunc turns a function with the right signature into a creates admin buildpack handler
type CreatesAdminBuildpackHandlerFunc func(CreatesAdminBuildpackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreatesAdminBuildpackHandlerFunc) Handle(params CreatesAdminBuildpackParams) middleware.Responder {
	return fn(params)
}

// CreatesAdminBuildpackHandler interface for that can handle valid creates admin buildpack params
type CreatesAdminBuildpackHandler interface {
	Handle(CreatesAdminBuildpackParams) middleware.Responder
}

// NewCreatesAdminBuildpack creates a new http.Handler for the creates admin buildpack operation
func NewCreatesAdminBuildpack(ctx *middleware.Context, handler CreatesAdminBuildpackHandler) *CreatesAdminBuildpack {
	return &CreatesAdminBuildpack{Context: ctx, Handler: handler}
}

/*CreatesAdminBuildpack swagger:route POST /buildpacks buildpacks createsAdminBuildpack

Creates an admin Buildpack

curl --insecure -i %s/v2/buildpacks -X POST -H 'Authorization: %s' -d '%s'

*/
type CreatesAdminBuildpack struct {
	Context *middleware.Context
	Handler CreatesAdminBuildpackHandler
}

func (o *CreatesAdminBuildpack) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreatesAdminBuildpackParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
