// Code generated by go-swagger; DO NOT EDIT.

package buildpacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveBuildpackHandlerFunc turns a function with the right signature into a retrieve buildpack handler
type RetrieveBuildpackHandlerFunc func(RetrieveBuildpackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveBuildpackHandlerFunc) Handle(params RetrieveBuildpackParams) middleware.Responder {
	return fn(params)
}

// RetrieveBuildpackHandler interface for that can handle valid retrieve buildpack params
type RetrieveBuildpackHandler interface {
	Handle(RetrieveBuildpackParams) middleware.Responder
}

// NewRetrieveBuildpack creates a new http.Handler for the retrieve buildpack operation
func NewRetrieveBuildpack(ctx *middleware.Context, handler RetrieveBuildpackHandler) *RetrieveBuildpack {
	return &RetrieveBuildpack{Context: ctx, Handler: handler}
}

/*RetrieveBuildpack swagger:route GET /buildpacks/{guid} buildpacks retrieveBuildpack

Retrieve a Particular Buildpack

curl --insecure -i %s/v2/buildpacks/{guid} -X GET -H 'Authorization: %s'

*/
type RetrieveBuildpack struct {
	Context *middleware.Context
	Handler RetrieveBuildpackHandler
}

func (o *RetrieveBuildpack) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRetrieveBuildpackParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
